package enumsP2P;

/*Generated by MPS */


public class Utils {
  public enum State {
    initial("initial state"),
    register("register state"),
    injected("injected state"),
    board("board state"),
    match("match state"),
    purchased("purchased state");

    private final String value;
    State(String value) {
      this.value = value;
    }
    public String getValue() {
      return this.value;
    }

    public static State fromValue(String value) {
      for (State it : State.values()) {
        if (it.value.equals(value)) {
          return it;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

  }

}
